package:
  name: mlib-mgroth0
  version: 0.0.42
source:
  path: .
build:
  script: python -m pip install --no-deps --ignore-installed .
requirements:
  build:
  - python
  - pip
  run:
  - colorama ==0.4.3
  - imageio ==2.8.0
  - packaging ==20.4
  - pexpect ==4.8.0
  - python ==3.8.3
  - pyyaml ==5.3.1
  - scipy ==1.4.1
  - wolframclient ==1.1.4
test:
  imports: mlib
