package:
  name: mlib-mgroth0
  version: 0.0.18

#source:
#  git_rev:
#  git_url:

requirements:
  build:
    - python
    - setuptools

  run:
    - python

#test:
#  imports:
#    -
#
#about:
#  home: