
package:
  name: mlib-mgroth0
  version: 0.0.35
source:
  path: .
requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python ==3.8.3
    - numpy ==1.18.5

    - ca-certificates ==2020.6.20
    - certifi ==2020.6.20
    - colorama ==0.4.3
    - freetype ==2.10.2
    - imageio ==2.8.0
    - jpeg ==9d
    - libblas ==3.8.0
    - libcblas ==3.8.0
    - libcxx ==10.0.0
    - libffi ==3.2.1
    - libgfortran ==4.0.0
    - liblapack ==3.8.0
    - libopenblas ==0.3.9
    - libpng ==1.6.37
    - libtiff ==4.1.0
    - libwebp-base ==1.1.0
    - llvm-openmp ==10.0.0
    - lz4-c ==1.9.2
    - ncurses ==6.1
    - numpy ==1.18.5
    - olefile ==0.46
    - openssl ==1.1.1g
    - packaging ==20.4
    - pexpect ==4.8.0
    - pillow ==7.1.2
    - pip ==20.1.1
    - ptyprocess ==0.6.0
    - pyparsing ==2.4.7
    - python ==3.8.3
    - python_abi ==3.8
    - pyyaml ==5.3.1
    - readline ==8.0
    - scipy ==1.4.1
    - setuptools ==47.3.1
    - six ==1.15.0
    - sqlite ==3.30.1
    - tk ==8.6.10
    - wheel ==0.34.2
    - xz ==5.2.5
    - yaml ==0.2.5
    - zlib ==1.2.11
    - zstd ==1.4.4

# having this section means creating a test env
# removing this seciton avoids creating a test env completely
test:
  imports:
    - mlib
