package:
  name: mlib-mgroth0
  version: 0.0.27

source:
  path: .
#  git_rev:
#  git_url:
#build:
#  number: 0
#  script: "$HOME""/miniconda3/envs/build/bin/python setup.py sdist bdist_wheel"

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - mlib

#about:
#  home: