
package:
  name: mlib-mgroth0
  version: 0.0.36
source:
  path: .
requirements:
  build:
    - python
    - pip #requires setuptools which reqs wheel
  run:
    - python ==3.8.3
    - numpy ==1.18.5

    - colorama ==0.4.3
    - imageio ==2.8.0
    - packaging ==20.4
    - pexpect ==4.8.0
    - python ==3.8.3
    - pyyaml ==5.3.1
    - scipy ==1.4.1

# having this section means creating a test env
# removing this seciton avoids creating a test env completely
test:
  imports:
    - mlib
